favorite = input("What is your favorite animal? \n>")
why = input(f"Why is a {favorite} your favorite animal \n>")
where = input(f"Where is it found?\n> ")
food = input(f"What do the like to eat?\n >")
fact = input("What is a fun fact about your animal?\n >")
fur = input("Does your animal have fur, scales, or just skin?\n >")
color = input(f"What is the color of your animal's {fur}\n >")
movement = input("How does your animal move around?\n >")
size = input("Is your animal large or small?\n >")
type = input("Is your favorite animal a mammal, reptile, or insect?\n >")

print(f"Your favorite animal is {favorite} because they are {why}.")
print(f"They live in {where}, and like to eat {food}.")
print(f"They have {color} {fur}, and move around by {movement}.")
print(f"Your favorite animal is a {size} {type}.")
print(f"And a fun fact about your animal is {fact}.")