answer1 = float(input("Number less than 5\n >"))
print(answer1 < 5)
answer2 = input("How old did George Boole live to be")
print(answer2 == "49")
answer3 = float(input("List a number greater than 10.\n >"))
print(answer3 > 10)
answer4 = input("Enter a word that ryhmes with orange\n >")
print(answer4 == "None")
answer5 = int(input("Enter the only number that is not prime nor composite\n >"))
print(answer5 == 1)

lanswer1 = int(input("What is a number less than 5 and greater than -5\n >"))
print(lanswer1 < 5 and lanswer1 > -2)
lanswer2 = int(input("What is a number greater than 6 or less than 6\n >"))
print(lanswer2 > 6 or lanswer2 < 6)
lanswer3 = int(input("Don't input 5\n >"))
print(lanswer3 != 5)